/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/max/projects/catkin_ws/src/transitbuddy/transitbuddy_msgs/msg/LineWithIDArray.msg
 *
 */


#ifndef TRANSITBUDDY_MSGS_MESSAGE_LINEWITHIDARRAY_H
#define TRANSITBUDDY_MSGS_MESSAGE_LINEWITHIDARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <transitbuddy_msgs/LineWithID.h>

namespace transitbuddy_msgs
{
template <class ContainerAllocator>
struct LineWithIDArray_
{
  typedef LineWithIDArray_<ContainerAllocator> Type;

  LineWithIDArray_()
    : header()
    , lines()  {
    }
  LineWithIDArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lines(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::transitbuddy_msgs::LineWithID_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::transitbuddy_msgs::LineWithID_<ContainerAllocator> >::other >  _lines_type;
  _lines_type lines;




  typedef boost::shared_ptr< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct LineWithIDArray_

typedef ::transitbuddy_msgs::LineWithIDArray_<std::allocator<void> > LineWithIDArray;

typedef boost::shared_ptr< ::transitbuddy_msgs::LineWithIDArray > LineWithIDArrayPtr;
typedef boost::shared_ptr< ::transitbuddy_msgs::LineWithIDArray const> LineWithIDArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace transitbuddy_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'transitbuddy_msgs': ['/home/max/projects/catkin_ws/src/transitbuddy/transitbuddy_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5afd1a2c369b484ddaa84e2067b45f01";
  }

  static const char* value(const ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5afd1a2c369b484dULL;
  static const uint64_t static_value2 = 0xdaa84e2067b45f01ULL;
};

template<class ContainerAllocator>
struct DataType< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transitbuddy_msgs/LineWithIDArray";
  }

  static const char* value(const ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
transitbuddy_msgs/LineWithID[] lines\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: transitbuddy_msgs/LineWithID\n\
int64 id\n\
int64 type\n\
geometry_msgs/Point[] p\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct LineWithIDArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transitbuddy_msgs::LineWithIDArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lines[]" << std::endl;
    for (size_t i = 0; i < v.lines.size(); ++i)
    {
      s << indent << "  lines[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::transitbuddy_msgs::LineWithID_<ContainerAllocator> >::stream(s, indent + "    ", v.lines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSITBUDDY_MSGS_MESSAGE_LINEWITHIDARRAY_H
