/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/max/projects/catkin_ws/src/transitbuddy/transitbuddy_msgs/msg/PoseWithID.msg
 *
 */


#ifndef TRANSITBUDDY_MSGS_MESSAGE_POSEWITHID_H
#define TRANSITBUDDY_MSGS_MESSAGE_POSEWITHID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace transitbuddy_msgs
{
template <class ContainerAllocator>
struct PoseWithID_
{
  typedef PoseWithID_<ContainerAllocator> Type;

  PoseWithID_()
    : id(0)
    , valid(false)
    , pose()  {
    }
  PoseWithID_(const ContainerAllocator& _alloc)
    : id(0)
    , valid(false)
    , pose(_alloc)  {
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;




  typedef boost::shared_ptr< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PoseWithID_

typedef ::transitbuddy_msgs::PoseWithID_<std::allocator<void> > PoseWithID;

typedef boost::shared_ptr< ::transitbuddy_msgs::PoseWithID > PoseWithIDPtr;
typedef boost::shared_ptr< ::transitbuddy_msgs::PoseWithID const> PoseWithIDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace transitbuddy_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'transitbuddy_msgs': ['/home/max/projects/catkin_ws/src/transitbuddy/transitbuddy_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a182e8ad566ba359c0bec7906132fc7";
  }

  static const char* value(const ::transitbuddy_msgs::PoseWithID_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a182e8ad566ba35ULL;
  static const uint64_t static_value2 = 0x9c0bec7906132fc7ULL;
};

template<class ContainerAllocator>
struct DataType< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "transitbuddy_msgs/PoseWithID";
  }

  static const char* value(const ::transitbuddy_msgs::PoseWithID_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n\
bool valid\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const ::transitbuddy_msgs::PoseWithID_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.valid);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PoseWithID_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::transitbuddy_msgs::PoseWithID_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::transitbuddy_msgs::PoseWithID_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRANSITBUDDY_MSGS_MESSAGE_POSEWITHID_H
